### ISSUE TITLE
Split akka-http servers, such as pump and communicatr, out of commands project.

### ISSUE THREAD

**Issue by oli-kitty** [47deg/TAFutureWork#12]

**Comment by toddburnside** [comment]
### Commands Project

#### Current State
The purpose of the code in the commands sbt project is not well defined. It contains a large number of what I would the name of the project would suggest: executables that perform a task of some sort, then exit. However, it also contains several executable that are actually Akka http servers.

#### Suggestion
Break each Akka http server into its own project. These Akka http servers are:
- TableJanitorCommand
- SqsTaskRunnerServer
- RepoBasedCommunicator
- PandaExpressServer
- Communicator
- Pump
The remaining commands could examined to determine if additional splits could be made. TrueAccord Engage related commands are an obvious candidate, but there are likely others.

Some of the benefits of this are:
- Simplify the project dependencies for each project.
- Make each project easier to understand.
- Start to get to the point where responsibility for a project can be assigned to an individual team/pod.
