### ISSUE TITLE
Update database connection pool/thread pool sizes.

### ISSUE THREAD

**Issue by oli-kitty** [47deg/TAFutureWork#4]

**Comment by toddburnside** [comment]
### Database Connection/Thread Pools

#### Current State
HikariCP, which manages the database connections, seems to be configured in a way that may not make sense.  HikariCP is currently configured to use 150 maximum connections and 75 threads for the API server and some of the commands. Allowing a machine to create too many connections can lead to shortage in the number of connections that keep running.  Allowing a machine to create too many threads can lead to thread starvation issues. The recommended starting place for connection pool sizing is approximately 2 per CPU core. This is drastically different than the current configuration.

#### Suggestion
Examine pool and thread connections in the api and all of the commands and set them to the recommended sizes based on the compute instances they are running on. The logs should then be monitored for any connection issues that might arise.

Note that this work is required before any work can be done on dividing the API, or we will deplete the allowable connections to the database server.
